// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'he'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	about: {
		/**
		 * A​b​o​u​t​ ​M​e
		 */
		aboutMe: string
	}
	navbar: {
		/**
		 * A​b​o​u​t
		 */
		about: string
		/**
		 * S​k​i​l​l​s
		 */
		skills: string
		/**
		 * E​x​p​e​r​i​e​n​c​e
		 */
		experience: string
		/**
		 * C​e​r​t​i​f​i​c​a​t​e​s
		 */
		certificates: string
		/**
		 * C​o​n​t​a​c​t
		 */
		contact: string
	}
}

export type TranslationFunctions = {
	about: {
		/**
		 * About Me
		 */
		aboutMe: () => LocalizedString
	}
	navbar: {
		/**
		 * About
		 */
		about: () => LocalizedString
		/**
		 * Skills
		 */
		skills: () => LocalizedString
		/**
		 * Experience
		 */
		experience: () => LocalizedString
		/**
		 * Certificates
		 */
		certificates: () => LocalizedString
		/**
		 * Contact
		 */
		contact: () => LocalizedString
	}
}

export type Formatters = {}
