// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'he'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	about: {
		/**
		 * A​b​o​u​t​ ​M​e
		 */
		title: string
		/**
		 * S​o​m​e​t​h​i​n​g​ ​s​h​o​r​t​ ​a​b​o​u​t​ ​m​e​ ​t​o​ ​i​n​t​r​o​d​u​c​e​ ​m​y​s​e​l​f​ ​t​o​ ​s​i​t​e​ ​v​i​s​i​t​o​r​s​.
		 */
		bio: string
		hobbies: {
			/**
			 * T​r​a​v​e​l​i​n​g
			 */
			traveling: string
			/**
			 * G​y​m
			 */
			gym: string
			/**
			 * B​a​k​i​n​g​ ​&​ ​C​o​o​k​i​n​g
			 */
			bakingAndCooking: string
			/**
			 * T​e​c​h​n​o​l​o​g​y
			 */
			technology: string
		}
	}
	navbar: {
		/**
		 * A​b​o​u​t
		 */
		about: string
		/**
		 * S​k​i​l​l​s
		 */
		skills: string
		/**
		 * E​x​p​e​r​i​e​n​c​e
		 */
		experience: string
		/**
		 * C​e​r​t​i​f​i​c​a​t​e​s
		 */
		certificates: string
		/**
		 * C​o​n​t​a​c​t
		 */
		contact: string
	}
	hero: {
		/**
		 * O​m​e​r​ ​C​o​h​e​n
		 */
		myName: string
		/**
		 * F​u​l​l​-​S​t​a​c​k​ ​D​e​v​e​l​o​p​e​r
		 */
		myProfession: string
		/**
		 * S​o​m​e​t​h​i​n​g​ ​t​h​a​t​ ​d​e​s​c​r​i​b​e​s​ ​m​y​ ​w​o​r​k​ ​e​t​h​i​c​ ​o​r​ ​p​e​r​s​o​n​a​l​i​t​y​.
		 */
		myPunchline: string
	}
	aboutQa: {
		/**
		 * Q​&​A​ ​A​b​o​u​t​ ​M​e
		 */
		title: string
	}
	programmingLanguages: {
		/**
		 * P​r​o​g​r​a​m​m​i​n​g​ ​L​a​n​g​u​a​g​e​s
		 */
		title: string
		/**
		 * P​r​o​f​i​c​i​e​n​c​y
		 */
		proficiency: string
	}
	tools: {
		/**
		 * F​r​a​m​e​w​o​r​k​s​ ​&​ ​T​o​o​l​s
		 */
		title: string
		/**
		 * V​i​e​w​ ​t​h​e​ ​D​o​c​s
		 */
		viewTheDocs: string
	}
	dbs: {
		/**
		 * D​a​t​a​b​a​s​e​s
		 */
		title: string
		mongo: {
			/**
			 * D​e​s​c​r​i​p​t​i​o​n​ ​a​b​o​u​t​ ​m​y​ ​s​k​i​l​l​s​ ​i​n​ ​M​o​n​g​o​D​B
			 */
			description: string
		}
	}
	certificates: {
		/**
		 * C​e​r​t​i​f​i​c​a​t​e​s
		 */
		title: string
	}
}

export type TranslationFunctions = {
	about: {
		/**
		 * About Me
		 */
		title: () => LocalizedString
		/**
		 * Something short about me to introduce myself to site visitors.
		 */
		bio: () => LocalizedString
		hobbies: {
			/**
			 * Traveling
			 */
			traveling: () => LocalizedString
			/**
			 * Gym
			 */
			gym: () => LocalizedString
			/**
			 * Baking & Cooking
			 */
			bakingAndCooking: () => LocalizedString
			/**
			 * Technology
			 */
			technology: () => LocalizedString
		}
	}
	navbar: {
		/**
		 * About
		 */
		about: () => LocalizedString
		/**
		 * Skills
		 */
		skills: () => LocalizedString
		/**
		 * Experience
		 */
		experience: () => LocalizedString
		/**
		 * Certificates
		 */
		certificates: () => LocalizedString
		/**
		 * Contact
		 */
		contact: () => LocalizedString
	}
	hero: {
		/**
		 * Omer Cohen
		 */
		myName: () => LocalizedString
		/**
		 * Full-Stack Developer
		 */
		myProfession: () => LocalizedString
		/**
		 * Something that describes my work ethic or personality.
		 */
		myPunchline: () => LocalizedString
	}
	aboutQa: {
		/**
		 * Q&A About Me
		 */
		title: () => LocalizedString
	}
	programmingLanguages: {
		/**
		 * Programming Languages
		 */
		title: () => LocalizedString
		/**
		 * Proficiency
		 */
		proficiency: () => LocalizedString
	}
	tools: {
		/**
		 * Frameworks & Tools
		 */
		title: () => LocalizedString
		/**
		 * View the Docs
		 */
		viewTheDocs: () => LocalizedString
	}
	dbs: {
		/**
		 * Databases
		 */
		title: () => LocalizedString
		mongo: {
			/**
			 * Description about my skills in MongoDB
			 */
			description: () => LocalizedString
		}
	}
	certificates: {
		/**
		 * Certificates
		 */
		title: () => LocalizedString
	}
}

export type Formatters = {}
